config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client
  include Mongoid::Document
  field :client_type, type: String
  field :name, type: String
  field :channel, type: String
  field :product_name, type: String

  has_and_belongs_to_many :products

    def to_s
        name
    end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  field :product_status, type: String
  field :product_code, type: String
  field :nature_type, type: String
  field :product_start_date_sales, type: Date
  field :product_end_date_sales, type: Date

  embeds_one :rule_set
  accepts_nested_attributes_for :rule_set, class_name: "RuleSet"

  has_and_belongs_to_many :clients
end

app/models/rule_set.rb
class RuleSet
  include Mongoid::Document

  field :claim_limit, type: String
  field :number_of_claims_allowed, type: String
  field :post_first_claim, type: String
  field :excess_fee_for_repair, type: String
  field :excess_fee_for_replacement, type: String
  field :excess_fee_time_limit_in_days, type: String
  field :coverage_type, type: String
  field :tenure, type: String
  field :logistics, type: String
  field :service_level_promise, type: String
  field :salvage, type: String
  field :settlement_type, type: String
  field :waiting_period_for_claim, type: String
  field :allowed_brands, type: String
  field :allowed_models, type: String
  field :allowed_device_types, type: String

  embedded_in :product, inverse_of: :rule_set
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:client_type, :name, :channel, :product_name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.build_rule_set
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :product_status,
        :product_code,
        :nature_type,
        :product_start_date_sales,
        :product_end_date_sales,
        :rule_set,
        client_ids: []
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_type %>
    <%= form.text_field :client_type %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :channel %>
    <%= form.text_field :channel %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Client type</th>
      <th>Name</th>
      <th>Channel</th>
      <th>Product name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.client_type %></td>
        <td><%= client.name %></td>
        <td><%= client.channel %></td>
        <td><%= client.product_name %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client type:</strong>
  <%= @client.client_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @client.channel %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @client.product_name %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mpro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_status %>
    <%= form.text_field :product_status %>
  </div>

  <div class="field">
    <%= form.label :product_code %>
    <%= form.text_field :product_code %>
  </div>

  <div class="field">
    <%= form.label :nature_type %>
    <%= form.text_field :nature_type %>
  </div>

  <div class="field">
    <%= form.label :product_start_date_sales %>
    <%= form.text_field :product_start_date_sales %>
  </div>

  <div class="field">
    <%= form.label :product_end_date_sales %>
    <%= form.text_field :product_end_date_sales %>
  </div>

  <div class="field">
    <%= form.label :clients %>
    <%= form.collection_check_boxes(:client_ids, Client.all, :id, :to_s) %>
  </div>

  <div class="field">
  <p><strong>Rules:</strong></p>
    <%= form.fields_for :rule_set  do |builder| %>
     <table>
       <tr>
         <td><%= builder.label :claim_limit %></td>
         <td><%= builder.text_field :claim_limit %></td>
       </tr>
       <tr>
         <td><%= builder.label :number_of_claims_allowed %></td>
         <td><%= builder.text_field :number_of_claims_allowed %></td>
       </tr>
       <tr>
         <td><%= builder.label :post_first_claim %></td>
         <td><%= builder.text_field :post_first_claim %></td>
       </tr>
       <tr>
         <td><%= builder.label :excess_fee_for_repair %></td>
          <td><%= builder.text_field :excess_fee_for_repair %></td>
       </tr>
       <tr>
         <td><%= builder.label :excess_fee_for_replacement %></td>
         <td><%= builder.text_field :excess_fee_for_replacement %></td>
       </tr>
       <tr>
         <td><%= builder.label :excess_fee_time_limit_in_days %></td>
         <td><%= builder.text_field :excess_fee_time_limit_in_days %></td>
       </tr>
     </table>
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Product status</th>
      <th>Product code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_status %></td>
        <td><%= product.product_code %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product status:</strong>
  <%= @product.product_status %>
</p>

<p>
  <strong>Product code:</strong>
  <%= @product.product_code %>
</p>

<p>
  <strong>Nature Type:</strong>
  <%= @product.nature_type %>
</p>

<p>
  <strong>Product Start Date:</strong>
  <%= @product.product_start_date_sales %>
</p>

<p>
  <strong>Product End Date:</strong>
  <%= @product.product_end_date_sales %>
</p>

<p>
  <strong>Clients:</strong>
  <ul>
    <% @product.clients.each do |c| %>
        <li><%= c %></li>
    <% end %>
    </ul>
</p>

<p>
  <strong>Rules:</strong>
  <p><%= @product.rule_set.claim_limit if @product.rule_set.present? %></p>
  <p><%= @product.rule_set.number_of_claims_allowed if @product.rule_set.present? %></p>
  <p><%= @product.rule_set.post_first_claim if @product.rule_set.present? %></p>
  <p><%= @product.rule_set.excess_fee_for_repair if @product.rule_set.present? %></p>
  <p><%= @product.rule_set.excess_fee_for_replacement if @product.rule_set.present? %></p>
  <p><%= @product.rule_set.excess_fee_time_limit_in_days if @product.rule_set.present? %></p>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>